default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lowercase-subject
        name: lowercase-subject
        entry: bash -c 'grep -q "^[a-z]" "$1" || { echo "Subject must be lowercase"; exit 1; }' --
        language: system
        stages: [commit-msg]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        files: ^go\\.mod$|^.*\\.go$
      - id: go-imports
        files: ^go\\.mod$|^.*\\.go$
      - id: no-go-testing
        files: ^go\\.mod$|^.*\\.go$
      - id: golangci-lint
        files: ^go\\.mod$|^.*\\.go$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose, --strict, build, ci, docs, feat, fix, chore, test, custom, perf, refactor, revert, test]

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.34.0
    hooks:
      - id: ggshield
        name: GitGuardian Shield
        language_version: python3
        stages: [pre-commit]
